### ISSUE TITLE
Possibilty of schema update for the review process

### ISSUE THREAD

**Issue by steull** [OpenEnergyPlatform/oemetadata#112]
Update schema.js with updated description and add further fields.
- [x] Description
- [x] Example
- [x] Badge
- [x] ✕ Review field stronglyRecommended (rejected)

**Comment by steull** [comment]
The schema is now updated. For the stronglyRecommended field, a final decision should be made whether this is only the Iron Badges or also other fields.

**Comment by christian-rli** [comment]
Thank you @steull . In my opinion the field should take a boolean value. Also it should be independent of the badges. The idea behind the information in stronglyRecommended was that the reviewer get

**Comment by christian-rli** [comment]
Thank you for your thoughts @chrwm ! As you quote, the original idea for the strongly recommended field was to give the reviewer a reject option for certain inputs. Not all fields are created equal. Some are a technical necessity for upload, like column descriptions, some have legal significance, like the license necessary to publish data on the OEP. 

Our motivation was to generate the review process page entirely from the schema. Since the iron badge only signifies the technically necessary fields for an upload, we wanted a way to include a way to label other no-go-input.

After more discussions, especially with @jh-RLI however, we concluded that this concern really only applies to the license information. It's possible to implement that exception in the review process without the schema, which is less elegant, but not a huge drama either. This would keep the schema clean and won't clutter it for a platform-specific use case. So I decided against the field stronglyRecommended after all.

**Comment by christian-rli** [comment]
I encountered another issue. The use of the keys `description`, `example`, `type`, `badge` and `title` is not consistent. 

(a) Every simple object has all five of them.

(b) In objects that contain a simple list (e.g. `languages` and `keywords`), `type`, `badge` and `title` go one level deeper into an `items` object. `type` and `badge` disappear from the parent object, while `title` is duplicated. The `example` given in the object contains a list with several entries. This isn't wrong, strictly speaking. However, we don't have examples with lists that contain other objects, which would be a logical consequence. The example entry should therefore go into the lowest level and be a single entry.

(c) The same movement of keys holds true for objects that contain a list of other objects (e.g. `licenses`). However, the lower object does have a new `description` and since there are new keys in the lower object, there are new `description`s, `badge`s and `title`s for them as well. So at the lowest level there are all five keys again

For consistency and cleaner code, I need/want access to all five keys on one level. This is possible in (a) and (c). (b) ought to be repaired. Fundamentally, I see two ways to achieve this:

1. Add a `description` and `example` to the lowest level (in items) of every simple list (optionally remove example list in the parent object)
2. Bring `badge` one level up (deal with type separately later, as it's not strictly important now)

I strongly advocate for 1, since it's cleaner and more consistent to always have all descriptive keys available on the lowest level. I will implement it in this way for the review process and then update here accordingly unless there are any objections in the mean time @jh-RLI @chrwm @Ludee

**Comment by jh-RLI** [comment]
Are you sure that you are using the latest versin of the schmea.json? The changes in this commit ca1c1fd add changes that are already in the latest schema.json in the `develop` branch.

**Comment by jh-RLI** [comment]
At some point, I didn't look closely at what he was doing. Maybe I missed that he was working on an outdated branch. I also think it would be best to close the current PR and create a new branch and try to incorporate the changes there. I mean, if you are sure that you can fix the merge conflicts, then that is also a good solution. However, you will lose some data that you will have to reinsert afterwards anyway. Also, I don't think the commits are small enough, and then you'd have to manually set yourself which lines in the conflict get fixed and which can stay. So seems to me like that would be a lot of extra work for little added value. 
We can mention @steull as a contributor in the changelog or PR.

PS: Yes good catch!

PSS: I already commented on this in another oeplatform issue. Wanted to point out to you here again that the [oemetadata now has a python package](https://pypi.org/project/oemetadata/). You can update that very easily by posting a release here on github. Then an automated pipeline is triggered that uploads the current content of the master branch to PyPi. Then you can import the oemeta data as a python module and don't have to manually copy json files and keep them up to date.

**Comment by christian-rli** [comment]
> ... We can mention @steull as a contributor in the changelog or PR.

I implemented all changes and will mention him in the PR

> PSS: I already commented on this in another oeplatform issue. Wanted to point out to you here again that the [oemetadata now has a python package](https://pypi.org/project/oemetadata/). You can update that very easily by posting a release here on github. Then an automated pipeline is triggered that uploads the current content of the master branch to PyPi. Then you can import the oemeta data as a python module and don't have to manually copy json files and keep them up to date.

Thanks for the info, It does seem like a cleaner way forward. However, (how) is it possible to import a certain version? Otherwise it would add another dependency whenever we make a code update. Let's discuss this in our meeting. If possible, I will implement an import once there's a working new release.

**Comment by jh-RLI** [comment]
You can import any version or just use the latest like this (same for template, example ....):

`from metadata.latest.schema import OEMETADATA_LATEST_SCHEMA`
