### ISSUE TITLE
Patch version v1.5.3? or go directly to v2.0.0

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/oemetadata#126]
I would suggest releasing a patch that includes the current changes.

This would help us make version 1.5 complete. The current changes fix the url in the context field, improve the schema and add more general things like the citation.cff and more.

The only real changes to the spec are the new fields for badges and examples in schema.json. These are not groundbreaking changes.

I could do a quick release now.

 Then we can move on to the other changes. 

What do you think @christian-rli @wingechr @Ludee @chrwm

**Comment by chrwm** [comment]
If you don't consider "new fields for badges and examples in schema.json" a feature that is fine for me. 

Otherwise we could also release a 1.5.X with

- The current changes fix the url in the context field,
- improve the schema
- add more general things like the citation.cff and more.

And include the badges and examples in schema.json as feature in 2.0.0 instead of an 1.6.0

**Comment by jh-RLI** [comment]
I would use the 2.0.0 for major changes like 100% compatibility with frictionlessData. I would like to release the badges soon and not use a major version but rather a minor version 1.6.0, otherwise this would seem like a very big update. We are adding a new feature but not changing the structure of the Oemetadata specification, so there are no breaking changes.

**Comment by christian-rli** [comment]
So without any objections it seems like there is a consensus in favor of a small release. 
Proposed procedure: 

- @Ludee please give your approval or reasons against
- @jh-RLI and I can implement the release
