### ISSUE TITLE
Tests to validate schema against meta schema  fail.

### ISSUE THREAD

**Issue by wingechr** [OpenEnergyPlatform/oemetadata#13]
## Problem

The function `jsonschema.validate` can not be used to validate a schema against the meta schema.

## Solution

Get rid of the folder `metadata/metaschema` and validate the schemata with `jsonschema.Draft7Validator.check_schema` for that (available, I think, since version 3.1, maybe earlier)

**Comment by Bachibouzouk** [comment]
I will wait on @4lm for this one

**Comment by 4lm** [comment]
Hi @wingechr and @Bachibouzouk,

@wingechr maybe I don't get what you mean, `jsonschema.validate` is IMO made for validating json instances against json schemas: [docs](https://python-jsonschema.readthedocs.io/en/stable/validate/).

The tests are successfully validating our schema against the metaschema with `jsonschema.validate`:  [here](https://github.com/OpenEnergyPlatform/metadata/blob/develop/tests/metadata/v130/test_schema.py#L21) and [here](https://github.com/OpenEnergyPlatform/metadata/blob/develop/tests/metadata/v140/test_schema.py#L21).

If you want to run the tests, follow [this](https://github.com/OpenEnergyPlatform/metadata#development) and [this](https://github.com/OpenEnergyPlatform/metadata#run-tests-locally-after-above-steps).

> Get rid of the folder metadata/metaschema and validate the schemata with jsonschema.Draft7Validator.check_schema for that (available, I think, since version 3.1, maybe earlier)

As I understand it, this repo is the place for our json schemas and shall be programming language agnostic. Right now it just happens to be, that we also have a Python implementation which delivers the schemas as library for usage in other Python programs/libraries. Other implementations in other languages might follow. That's why there is the json metaschema as physical copy in this repo, which is backed by a [test](https://github.com/OpenEnergyPlatform/metadata/blob/develop/tests/metadata/metaschema/draft07/test_schema.py) to guarantee, that the correct/unaltered json metaschema is used. I find it very good and explicit to have/use the metaschema in this repo and not some implicit library built-in version, also because other language implementations might follow.

**Comment by wingechr** [comment]
Weird. Those two tests fail for me when I run `pytest` (under windows, python 3.7.2).

That's why I suggested using `check_schema`. (According to [docs](https://python-jsonschema.readthedocs.io/en/stable/validate/#jsonschema.IValidator.check_schema), it is to be used to validate the given schema against a meta schema), 


But I suppose it's not a big issue.

**Comment by jh-RLI** [comment]
OpenEnergyPlatform/oeplatform#574

**Comment by Ludee** [comment]
Is this issue solved?

**Comment by wingechr** [comment]
soweit ich das sehen kann: nein. 

Ist aber nicht wirklich problematisch. Das Fehler ist ja **nicht**, dass keine Metadaten validiert werden können. Das funktioniert ja.

Der Feher ist, dass in den tests für das Paket auch versucht wird, das Schema selbst zu validieren.
