### ISSUE TITLE
Revision of the OEMetadata structure to improve usage and technical correctness

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/oemetadata#97]
@wingechr We talked about this in the project meeting last week. Could you please add a brief sketch of what you mean so we can discuss it and make it available to others?

I think if you could quickly change the structure of the Oemetada example to what you explained to me, that would help me and others understand it - I thought I understood, but I forgot what key you were talking about :) I think it was about resources or schema?

--> https://github.com/OpenEnergyPlatform/oemetadata/blob/develop/metadata/latest/example.json

**Comment by wingechr** [comment]
## OLD

* json metadata for table: 
```json
{
    "resources": [
        {
            "name": "<TABLE_NAME>"
            "schema": {...}
        }
    ],
    <METADATA>
}
```
* json metadata for datapackage: `DOES NOT EXIST` 

## PROPOSED NEW

* json metadata for table (aka resource): 
```json
{
    "name": "<TABLE_NAME>",
    "path": "<URL>",
    "schema": {...},
    <METADATA>    
}
```
* json metadata for datapackage:

```json
{
    "name": "<BUNDLE_NAME>",
    "resources": [
        {
            "name": "<TABLE_NAME_1>",
            "path": "<URL>",
            "schema": {...},
            <METADATA>    
        },
        {
            "name": "<TABLE_NAME_2>",
            "path": "<URL>",
            "schema": {...},
            <METADATA>    
        },
        ...
    ]
}
```

* `name` and `path` are required (by specs) for resource,
* `name` and `resources` are required for datapackage

**Comment by henhuy** [comment]
Agree with your proposal!

**Comment by wingechr** [comment]
sorry, one more correction: in the bundled datapackage.json that presumably is part of a zipped datapackage in a download, the resource `path` must be changed to the now local csv file that contains the table data. There can also be some more additional metadata values (like csv encoding) that don't make sense for data in the database, but for it's physical representation in a file when downloaded:

```json
{
    "name": "<BUNDLE_NAME>",
    "resources": [
        {
            "name": "<TABLE_NAME_1>",
            "path": "data/<PATH/TO/CSV.csv>,
            "encoding": "utf-8",
            "schema": {...},
            <METADATA>    
        },
        {
            "name": "<TABLE_NAME_2>",
            "path": "data/<PATH/TO/CSV.csv>,
            "encoding": "utf-8",
            "schema": {...},
            <METADATA>    
        },
        ...
    ]
}
```

**Comment by jh-RLI** [comment]
I added an example presenting what my understanding of the changes is. 
- [ressource](https://github.com/OpenEnergyPlatform/oemetadata/blob/feature/draft_updated_oem_ressourse_and_datapackge/metadata/oemetadata_16_wip/oem_16_ressource.json)
- [datapackage](https://github.com/OpenEnergyPlatform/oemetadata/blob/feature/draft_updated_oem_ressourse_and_datapackge/metadata/oemetadata_16_wip/oem_16_bundle.json)

One more thing, we have to figure out where to put the keys that have been stored in the old resources. 

``` json
"profile": "tabular-data-resource",
"name": "model_draft.oep_metadata_table_example_v152",
"path": "http://openenergyplatform.org/dataedit/view/model_draft/oep_metadata_table_example_v152",
"format": "PostgreSQL",
"encoding": "UTF-8", 
```

- name would duplicate the name of the metadata
- path is kinda duplicated with id
- profile ...

**Comment by wingechr** [comment]
just to be clear: the metadata is different when it is on the platform and when it is in a downloaded zip package.

most notably:

* `path`: on the server, it can be the url (and is redundant with the id) or it can be dropped entirely. BUT on in a local zip package it MUST be the relative path to the csv file (e.g. `data/table.csv`)

* `profile`, `encoding`, `format`, ...: on the server, they can (and should) be omitted entirely, because this is information only relevant for a local csv file.

as an example: i could upload a csv file with encoding iso-8556-1, but in the postgres database it will always be utf-8, so the encoding information becomes irrelevant. if i download it again though, the encoding of the csv file (once created) becomes relevant for the user again.

**Comment by jh-RLI** [comment]
True, we should then add functionality to the OEP upload and download that removes and adds this information?
Then the main change to the current oemetadata spec. would just be the removed resources key.

**Comment by wingechr** [comment]
yea. i think like this: 

* remove `profile`, `encoding`, ... from the specs and drop on upload
* `path` should stay part of the specs, because it is part of frictionless specs, but programmatically set it to url on upload
* `name` should be programmatically set to the table name
* on normal metadata download: don't change anything
* only in package download:
  * create new datapackage.json
  * get metadata for all the requested tables and put them into the `resources` array
  * programmatically add `profile`, `encoding`, for the resources csv data
  * programmatically change `path` in each resource to the csv file
